# Server Configuration
server:
  port: 8080

# DB Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionFacture
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

############## Email Config ##############
  mail:
    host: smtp.gmail.com
    port: 465
    username: your_email
    password: your_password
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


external:
  facturestoragePath: "src/main/resources/factures/"
