# Server Configuration
server:
  port: 8080

# DB Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionFacture
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

external:
  facturestoragePath: "/factures/"
